import { createContext, useContext } from 'react'
import { useAuth } from '../context/AuthContext.jsx'

// Best-effort translations, not yet reviewed by native speakers for most
// languages — keep the unverified warning in LanguageSettings until checked.
const translations = {
  en: { home: 'Home', chats: 'Chats', post: 'Post', alerts: 'Alerts', profile: 'Profile', welcomeTitle: 'Welcome to Schoolink', welcomeTagline: 'Your all-in-one platform for schools, staff, parents and communities.', signInEmail: 'Sign in with Email', continueGoogle: 'Continue with Google', continueGuest: 'Continue as Guest', agree: 'By continuing, you agree to our' },
  sn: { home: 'Kumba', chats: 'Nhaurwa', post: 'Nyora', alerts: 'Ziviso', profile: 'Purofairo', welcomeTitle: 'Tinokugamuchirai kuSchoolink', welcomeTagline: 'Nzvimbo imwe chete yezvikoro, vashandi, vabereki nenharaunda.', signInEmail: 'Pinda neEmail', continueGoogle: 'Enderera neGoogle', continueGuest: 'Enderera semueni', agree: 'Kana muchienderera mberi, munobvuma' },
  nd: { home: 'Ekhaya', chats: 'Izingxoxo', post: 'Bhala', alerts: 'Izaziso', profile: 'Iphrofayili', welcomeTitle: 'Siyalemukela ku-Schoolink', welcomeTagline: 'Inkundla eyodwa yezikolo, abasebenzi, abazali lomphakathi.', signInEmail: 'Ngena nge-Emeyili', continueGoogle: 'Qhubeka nge-Google', continueGuest: 'Qhubeka njengesihambi', agree: 'Ngokuqhubeka, uyavuma' },
  zu: { home: 'Ikhaya', chats: 'Izingxoxo', post: 'Thumela', alerts: 'Izaziso', profile: 'Iphrofayela', welcomeTitle: 'Siyakwamukela ku-Schoolink', welcomeTagline: 'Inkundla eyodwa yezikole, abasebenzi, abazali nemiphakathi.', signInEmail: 'Ngena nge-imeyili', continueGoogle: 'Qhubeka ngeGoogle', continueGuest: 'Qhubeka njengesivakashi', agree: 'Ngokuqhubeka, uyavuma' },
  xh: { home: 'Ikhaya', chats: 'Iincoko', post: 'Thumela', alerts: 'Izaziso', profile: 'Iprofayile', welcomeTitle: 'Wamkelekile kwi-Schoolink', welcomeTagline: 'Iqonga elinye lezikolo, abasebenzi, abazali noluntu.', signInEmail: 'Ngena nge-imeyile', continueGoogle: 'Qhubeka ngeGoogle', continueGuest: 'Qhubeka njengomndwendwe', agree: 'Ngokuqhubeka, uyavuma' },
  af: { home: 'Tuis', chats: 'Geselsies', post: 'Plaas', alerts: 'Kennisgewings', profile: 'Profiel', welcomeTitle: 'Welkom by Schoolink', welcomeTagline: 'Jou alles-in-een platform vir skole, personeel, ouers en gemeenskappe.', signInEmail: 'Teken in met E-pos', continueGoogle: 'Gaan voort met Google', continueGuest: 'Gaan voort as gas', agree: 'Deur voort te gaan, stem jy saam met ons' },
  ny: { home: 'Kunyumba', chats: 'Zokambirana', post: 'Lemba', alerts: 'Zidziwitso', profile: 'Mbiri', welcomeTitle: 'Takulandirani ku Schoolink', welcomeTagline: 'Nsanja imodzi ya masukulu, antchito, makolo ndi madera.', signInEmail: 'Lowani ndi Imelo', continueGoogle: 'Pitirizani ndi Google', continueGuest: 'Pitirizani ngati mlendo', agree: 'Mukapitiriza, mukuvomereza' },
  bem: { home: 'Ku ng\'anda', chats: 'Ukulanda', post: 'Lemba', alerts: 'Ukwishibisha', profile: 'Ifya pali imwe', welcomeTitle: 'Mwaiseni ku Schoolink', welcomeTagline: 'Icipande cimo ica masukulu, ababomfi, abafyashi na bantu.', signInEmail: 'Ingilamo na Email', continueGoogle: 'Twaleni na Google', continueGuest: 'Twaleni nge mweni', agree: 'Nga mwatwalilila, mwasumina' },
  sw: { home: 'Nyumbani', chats: 'Mazungumzo', post: 'Chapisha', alerts: 'Arifa', profile: 'Wasifu', welcomeTitle: 'Karibu Schoolink', welcomeTagline: 'Jukwaa lako moja la shule, wafanyakazi, wazazi na jamii.', signInEmail: 'Ingia kwa Barua pepe', continueGoogle: 'Endelea na Google', continueGuest: 'Endelea kama Mgeni', agree: 'Kwa kuendelea, unakubali' },
  yo: { home: 'Ile', chats: 'Ibaraẹnisọrọ', post: 'Fiweranṣẹ', alerts: 'Ikilọ', profile: 'Profaili', welcomeTitle: 'Kaabo si Schoolink', welcomeTagline: 'Ẹrọ kan ṣoṣo fun ile-iwe, oṣiṣẹ, obi ati agbegbe.', signInEmail: 'Wọle pẹlu Imeeli', continueGoogle: 'Tẹsiwaju pẹlu Google', continueGuest: 'Tẹsiwaju bi Alejo', agree: 'Nipa titẹsiwaju, o gba' },
  ig: { home: 'Ụlọ', chats: 'Mkparịta ụka', post: 'Zipu', alerts: 'Ọkwa', profile: 'Profaịlụ', welcomeTitle: 'Nnọọ na Schoolink', welcomeTagline: 'Ikpo okwu otu maka ụlọ akwụkwọ, ndị ọrụ, nne na nna na obodo.', signInEmail: 'Banye na Email', continueGoogle: 'Gaa n\'ihu na Google', continueGuest: 'Gaa n\'ihu dịka Onye ọbịa', agree: 'Site n\'ịga n\'ihu, ị kwenyere' },
  ha: { home: 'Gida', chats: 'Tattaunawa', post: 'Aikawa', alerts: 'Sanarwa', profile: 'Bayani', welcomeTitle: 'Barka da zuwa Schoolink', welcomeTagline: 'Dandali daya don makarantu, ma\'aikata, iyaye da al\'umma.', signInEmail: 'Shiga da Imel', continueGoogle: 'Ci gaba da Google', continueGuest: 'Ci gaba a matsayin Bako', agree: 'Ta ci gaba, kun yarda da' },
  am: { home: 'ቤት', chats: 'ውይይቶች', post: 'ለጥፍ', alerts: 'ማንቂያዎች', profile: 'መገለጫ', welcomeTitle: 'እንኳን ወደ Schoolink በደህና መጡ', welcomeTagline: 'ለትምህርት ቤቶች፣ ሰራተኞች፣ ወላጆች እና ማህበረሰቦች የተዋሃደ መድረክ።', signInEmail: 'በኢሜይል ይግቡ', continueGoogle: 'በGoogle ይቀጥሉ', continueGuest: 'እንደ እንግዳ ይቀጥሉ', agree: 'በመቀጠል ተስማምተዋል' },
  so: { home: 'Guriga', chats: 'Sheekaysiyo', post: 'Dir', alerts: 'Digniin', profile: 'Astaanta', welcomeTitle: 'Kusoo dhawoow Schoolink', welcomeTagline: 'Madal hal ah oo loogu talagalay dugsiyada, shaqaalaha, waalidiinta iyo bulshada.', signInEmail: 'Ku gal Email', continueGoogle: 'Ku sii wad Google', continueGuest: 'Ku sii wad sida Marti', agree: 'Adigoo sii wadaya, waad ogolaatay' },
  rw: { home: 'Murugo', chats: 'Ibiganiro', post: 'Ohereza', alerts: 'Imenyesha', profile: 'Umwirondoro', welcomeTitle: 'Murakaza neza kuri Schoolink', welcomeTagline: 'Urubuga rumwe rw\'amashuri, abakozi, ababyeyi n\'imiryango.', signInEmail: 'Injira ukoresheje Email', continueGoogle: 'Komeza ukoresheje Google', continueGuest: 'Komeza nk\'umushyitsi', agree: 'Mu gukomeza, wemeye' },
  st: { home: 'Lapeng', chats: 'Dipuisano', post: 'Romela', alerts: 'Ditemoso', profile: 'Boitsebiso', welcomeTitle: 'Rea o amohela ho Schoolink', welcomeTagline: 'Sethala se le seng sa dikolo, basebetsi, batswadi le baahi.', signInEmail: 'Kena ka Imeile', continueGoogle: 'Tswela pele ka Google', continueGuest: 'Tswela pele jwalo ka moeti', agree: 'Ka ho tswela pele, o dumela' },
  tn: { home: 'Gae', chats: 'Dipuisanyo', post: 'Romela', alerts: 'Dikitsiso', profile: 'Porofaele', welcomeTitle: 'Re a lo amogela mo Schoolink', welcomeTagline: 'Sethunya se le sengwe sa dikolo, badiri, batsadi le baagi.', signInEmail: 'Tsena ka Imeile', continueGoogle: 'Tswelela ka Google', continueGuest: 'Tswelela jaaka moeng', agree: 'Ka go tswelela, o a dumalana' },
  fr: { home: 'Accueil', chats: 'Discussions', post: 'Publier', alerts: 'Alertes', profile: 'Profil', welcomeTitle: 'Bienvenue sur Schoolink', welcomeTagline: 'Votre plateforme tout-en-un pour les écoles, le personnel, les parents et les communautés.', signInEmail: 'Se connecter par e-mail', continueGoogle: 'Continuer avec Google', continueGuest: 'Continuer en tant qu\'invité', agree: 'En continuant, vous acceptez notre' },
  pt: { home: 'Início', chats: 'Conversas', post: 'Publicar', alerts: 'Alertas', profile: 'Perfil', welcomeTitle: 'Bem-vindo ao Schoolink', welcomeTagline: 'Sua plataforma completa para escolas, funcionários, pais e comunidades.', signInEmail: 'Entrar com E-mail', continueGoogle: 'Continuar com o Google', continueGuest: 'Continuar como Convidado', agree: 'Ao continuar, você concorda com nossos' },
  es: { home: 'Inicio', chats: 'Chats', post: 'Publicar', alerts: 'Alertas', profile: 'Perfil', welcomeTitle: 'Bienvenido a Schoolink', welcomeTagline: 'Tu plataforma todo en uno para escuelas, personal, padres y comunidades.', signInEmail: 'Iniciar sesión con correo', continueGoogle: 'Continuar con Google', continueGuest: 'Continuar como invitado', agree: 'Al continuar, aceptas nuestros' },
  de: { home: 'Start', chats: 'Chats', post: 'Beitrag', alerts: 'Benachrichtigungen', profile: 'Profil', welcomeTitle: 'Willkommen bei Schoolink', welcomeTagline: 'Deine Komplettlösung für Schulen, Personal, Eltern und Gemeinschaften.', signInEmail: 'Mit E-Mail anmelden', continueGoogle: 'Mit Google fortfahren', continueGuest: 'Als Gast fortfahren', agree: 'Indem du fortfährst, stimmst du unseren' },
  it: { home: 'Home', chats: 'Chat', post: 'Pubblica', alerts: 'Avvisi', profile: 'Profilo', welcomeTitle: 'Benvenuto su Schoolink', welcomeTagline: 'La tua piattaforma completa per scuole, personale, genitori e comunità.', signInEmail: 'Accedi con Email', continueGoogle: 'Continua con Google', continueGuest: 'Continua come ospite', agree: 'Continuando, accetti i nostri' },
  nl: { home: 'Start', chats: 'Chats', post: 'Plaatsen', alerts: 'Meldingen', profile: 'Profiel', welcomeTitle: 'Welkom bij Schoolink', welcomeTagline: 'Jouw alles-in-één platform voor scholen, personeel, ouders en gemeenschappen.', signInEmail: 'Inloggen met e-mail', continueGoogle: 'Doorgaan met Google', continueGuest: 'Doorgaan als gast', agree: 'Door door te gaan, ga je akkoord met onze' },
  ru: { home: 'Главная', chats: 'Чаты', post: 'Опубликовать', alerts: 'Уведомления', profile: 'Профиль', welcomeTitle: 'Добро пожаловать в Schoolink', welcomeTagline: 'Единая платформа для школ, сотрудников, родителей и сообществ.', signInEmail: 'Войти по Email', continueGoogle: 'Продолжить с Google', continueGuest: 'Продолжить как гость', agree: 'Продолжая, вы соглашаетесь с нашими' },
  pl: { home: 'Start', chats: 'Czaty', post: 'Publikuj', alerts: 'Powiadomienia', profile: 'Profil', welcomeTitle: 'Witamy w Schoolink', welcomeTagline: 'Twoja platforma dla szkół, pracowników, rodziców i społeczności.', signInEmail: 'Zaloguj się przez e-mail', continueGoogle: 'Kontynuuj z Google', continueGuest: 'Kontynuuj jako gość', agree: 'Kontynuując, akceptujesz nasze' },
  uk: { home: 'Головна', chats: 'Чати', post: 'Опублікувати', alerts: 'Сповіщення', profile: 'Профіль', welcomeTitle: 'Ласкаво просимо до Schoolink', welcomeTagline: 'Єдина платформа для шкіл, персоналу, батьків та громад.', signInEmail: 'Увійти через Email', continueGoogle: 'Продовжити з Google', continueGuest: 'Продовжити як гість', agree: 'Продовжуючи, ви погоджуєтесь з нашими' },
  ro: { home: 'Acasă', chats: 'Chat-uri', post: 'Postează', alerts: 'Alerte', profile: 'Profil', welcomeTitle: 'Bine ai venit pe Schoolink', welcomeTagline: 'Platforma ta completă pentru școli, personal, părinți și comunități.', signInEmail: 'Conectare cu Email', continueGoogle: 'Continuă cu Google', continueGuest: 'Continuă ca Vizitator', agree: 'Continuând, ești de acord cu' },
  el: { home: 'Αρχική', chats: 'Συνομιλίες', post: 'Δημοσίευση', alerts: 'Ειδοποιήσεις', profile: 'Προφίλ', welcomeTitle: 'Καλώς ήρθατε στο Schoolink', welcomeTagline: 'Η ολοκληρωμένη πλατφόρμα για σχολεία, προσωπικό, γονείς και κοινότητες.', signInEmail: 'Σύνδεση με Email', continueGoogle: 'Συνέχεια με Google', continueGuest: 'Συνέχεια ως Επισκέπτης', agree: 'Συνεχίζοντας, συμφωνείτε με' },
  sv: { home: 'Hem', chats: 'Chattar', post: 'Publicera', alerts: 'Aviseringar', profile: 'Profil', welcomeTitle: 'Välkommen till Schoolink', welcomeTagline: 'Din allt-i-ett-plattform för skolor, personal, föräldrar och samhällen.', signInEmail: 'Logga in med e-post', continueGoogle: 'Fortsätt med Google', continueGuest: 'Fortsätt som gäst', agree: 'Genom att fortsätta godkänner du våra' },
  tr: { home: 'Anasayfa', chats: 'Sohbetler', post: 'Gönder', alerts: 'Bildirimler', profile: 'Profil', welcomeTitle: 'Schoolink\'e Hoş Geldiniz', welcomeTagline: 'Okullar, personel, veliler ve topluluklar için hepsi bir arada platformunuz.', signInEmail: 'E-posta ile Giriş Yap', continueGoogle: 'Google ile Devam Et', continueGuest: 'Misafir Olarak Devam Et', agree: 'Devam ederek şartlarımızı kabul etmiş olursunuz' },
  zh: { home: '首页', chats: '聊天', post: '发布', alerts: '通知', profile: '个人资料', welcomeTitle: '欢迎使用 Schoolink', welcomeTagline: '为学校、教职工、家长和社区打造的一体化平台。', signInEmail: '使用邮箱登录', continueGoogle: '使用 Google 继续', continueGuest: '以访客身份继续', agree: '继续即表示您同意我们的' },
  ja: { home: 'ホーム', chats: 'チャット', post: '投稿', alerts: '通知', profile: 'プロフィール', welcomeTitle: 'Schoolinkへようこそ', welcomeTagline: '学校、教職員、保護者、コミュニティのためのオールインワンプラットフォーム。', signInEmail: 'メールでサインイン', continueGoogle: 'Googleで続ける', continueGuest: 'ゲストとして続ける', agree: '続行することで、以下に同意したことになります' },
  ko: { home: '홈', chats: '채팅', post: '게시', alerts: '알림', profile: '프로필', welcomeTitle: 'Schoolink에 오신 것을 환영합니다', welcomeTagline: '학교, 교직원, 학부모 및 커뮤니티를 위한 올인원 플랫폼.', signInEmail: '이메일로 로그인', continueGoogle: 'Google로 계속하기', continueGuest: '게스트로 계속하기', agree: '계속 진행하면 다음에 동의하는 것입니다' },
  hi: { home: 'होम', chats: 'चैट्स', post: 'पोस्ट करें', alerts: 'सूचनाएं', profile: 'प्रोफ़ाइल', welcomeTitle: 'Schoolink में आपका स्वागत है', welcomeTagline: 'स्कूलों, स्टाफ़, माता-पिता और समुदायों के लिए आपका ऑल-इन-वन प्लेटफ़ॉर्म।', signInEmail: 'ईमेल से साइन इन करें', continueGoogle: 'Google से जारी रखें', continueGuest: 'अतिथि के रूप में जारी रखें', agree: 'जारी रखकर, आप हमारी सहमति देते हैं' },
  bn: { home: 'হোম', chats: 'চ্যাট', post: 'পোস্ট করুন', alerts: 'সতর্কতা', profile: 'প্রোফাইল', welcomeTitle: 'Schoolink-এ স্বাগতম', welcomeTagline: 'স্কুল, কর্মী, অভিভাবক ও সম্প্রদায়ের জন্য আপনার সর্ব-ইন-ওয়ান প্ল্যাটফর্ম।', signInEmail: 'ইমেল দিয়ে সাইন ইন করুন', continueGoogle: 'Google দিয়ে চালিয়ে যান', continueGuest: 'অতিথি হিসেবে চালিয়ে যান', agree: 'চালিয়ে গেলে, আপনি সম্মত হচ্ছেন' },
  ur: { home: 'ہوم', chats: 'چیٹس', post: 'پوسٹ کریں', alerts: 'الرٹس', profile: 'پروفائل', welcomeTitle: 'Schoolink میں خوش آمدید', welcomeTagline: 'اسکولوں، عملے، والدین اور کمیونٹیز کے لیے آپ کا ہمہ جہت پلیٹ فارم۔', signInEmail: 'ای میل سے سائن ان کریں', continueGoogle: 'Google کے ساتھ جاری رکھیں', continueGuest: 'مہمان کے طور پر جاری رکھیں', agree: 'جاری رکھنے سے، آپ متفق ہیں' },
  pa: { home: 'ਹੋਮ', chats: 'ਗੱਲਬਾਤ', post: 'ਪੋਸਟ ਕਰੋ', alerts: 'ਚੇਤਾਵਨੀਆਂ', profile: 'ਪ੍ਰੋਫਾਈਲ', welcomeTitle: 'Schoolink ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ', welcomeTagline: 'ਸਕੂਲਾਂ, ਸਟਾਫ, ਮਾਪਿਆਂ ਅਤੇ ਭਾਈਚਾਰਿਆਂ ਲਈ ਤੁਹਾਡਾ ਪਲੇਟਫਾਰਮ।', signInEmail: 'ਈਮੇਲ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ', continueGoogle: 'Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ', continueGuest: 'ਮਹਿਮਾਨ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ', agree: 'ਜਾਰੀ ਰੱਖ ਕੇ, ਤੁਸੀਂ ਸਹਿਮਤ ਹੋ' },
  ta: { home: 'முகப்பு', chats: 'அரட்டைகள்', post: 'பதிவிடு', alerts: 'எச்சரிக்கைகள்', profile: 'சுயவிவரம்', welcomeTitle: 'Schoolink-க்கு வரவேற்கிறோம்', welcomeTagline: 'பள்ளிகள், ஊழியர்கள், பெற்றோர்கள் மற்றும் சமூகங்களுக்கான ஒரே தளம்.', signInEmail: 'மின்னஞ்சல் மூலம் உள்நுழைக', continueGoogle: 'Google உடன் தொடரவும்', continueGuest: 'விருந்தினராக தொடரவும்', agree: 'தொடர்வதன் மூலம், நீங்கள் ஒப்புக்கொள்கிறீர்கள்' },
  te: { home: 'హోమ్', chats: 'చాట్‌లు', post: 'పోస్ట్ చేయండి', alerts: 'హెచ్చరికలు', profile: 'ప్రొఫైల్', welcomeTitle: 'Schoolink కు స్వాగతం', welcomeTagline: 'పాఠశాలలు, సిబ్బంది, తల్లిదండ్రులు మరియు సంఘాల కోసం మీ ఆల్-ఇన్-వన్ వేదిక.', signInEmail: 'ఇమెయిల్‌తో సైన్ ఇన్ చేయండి', continueGoogle: 'Google తో కొనసాగించండి', continueGuest: 'అతిథిగా కొనసాగించండి', agree: 'కొనసాగించడం ద్వారా, మీరు అంగీకరిస్తున్నారు' },
  vi: { home: 'Trang chủ', chats: 'Trò chuyện', post: 'Đăng', alerts: 'Thông báo', profile: 'Hồ sơ', welcomeTitle: 'Chào mừng đến với Schoolink', welcomeTagline: 'Nền tảng toàn diện cho trường học, nhân viên, phụ huynh và cộng đồng.', signInEmail: 'Đăng nhập bằng Email', continueGoogle: 'Tiếp tục với Google', continueGuest: 'Tiếp tục với tư cách Khách', agree: 'Bằng việc tiếp tục, bạn đồng ý với' },
  th: { home: 'หน้าแรก', chats: 'แชท', post: 'โพสต์', alerts: 'การแจ้งเตือน', profile: 'โปรไฟล์', welcomeTitle: 'ยินดีต้อนรับสู่ Schoolink', welcomeTagline: 'แพลตฟอร์มครบวงจรสำหรับโรงเรียน บุคลากร ผู้ปกครอง และชุมชน', signInEmail: 'เข้าสู่ระบบด้วยอีเมล', continueGoogle: 'ดำเนินการต่อด้วย Google', continueGuest: 'ดำเนินการต่อในฐานะผู้เยี่ยมชม', agree: 'การดำเนินการต่อถือว่าคุณยอมรับ' },
  id: { home: 'Beranda', chats: 'Obrolan', post: 'Posting', alerts: 'Notifikasi', profile: 'Profil', welcomeTitle: 'Selamat Datang di Schoolink', welcomeTagline: 'Platform lengkap untuk sekolah, staf, orang tua, dan komunitas.', signInEmail: 'Masuk dengan Email', continueGoogle: 'Lanjutkan dengan Google', continueGuest: 'Lanjutkan sebagai Tamu', agree: 'Dengan melanjutkan, Anda menyetujui' },
  ms: { home: 'Laman Utama', chats: 'Sembang', post: 'Siar', alerts: 'Makluman', profile: 'Profil', welcomeTitle: 'Selamat Datang ke Schoolink', welcomeTagline: 'Platform lengkap anda untuk sekolah, kakitangan, ibu bapa dan komuniti.', signInEmail: 'Log Masuk dengan E-mel', continueGoogle: 'Teruskan dengan Google', continueGuest: 'Teruskan sebagai Tetamu', agree: 'Dengan meneruskan, anda bersetuju dengan' },
  fil: { home: 'Home', chats: 'Mga Chat', post: 'Mag-post', alerts: 'Mga Alerto', profile: 'Profile', welcomeTitle: 'Maligayang Pagdating sa Schoolink', welcomeTagline: 'Ang iyong all-in-one platform para sa mga paaralan, kawani, magulang at komunidad.', signInEmail: 'Mag-sign in gamit ang Email', continueGoogle: 'Magpatuloy gamit ang Google', continueGuest: 'Magpatuloy bilang Bisita', agree: 'Sa pagpapatuloy, sumasang-ayon ka sa aming' },
  ar: { home: 'الرئيسية', chats: 'المحادثات', post: 'نشر', alerts: 'التنبيهات', profile: 'الملف الشخصي', welcomeTitle: 'مرحبًا بك في Schoolink', welcomeTagline: 'منصتك الشاملة للمدارس والموظفين وأولياء الأمور والمجتمعات.', signInEmail: 'تسجيل الدخول بالبريد الإلكتروني', continueGoogle: 'المتابعة باستخدام Google', continueGuest: 'المتابعة كضيف', agree: 'بالمتابعة، فإنك توافق على' },
  he: { home: 'בית', chats: 'צ\'אטים', post: 'פרסם', alerts: 'התראות', profile: 'פרופיל', welcomeTitle: 'ברוכים הבאים ל-Schoolink', welcomeTagline: 'הפלטפורמה שלך לבתי ספר, צוות, הורים וקהילות.', signInEmail: 'התחבר עם אימייל', continueGoogle: 'המשך עם Google', continueGuest: 'המשך כאורח', agree: 'בהמשך, אתה מסכים ל' },
  fa: { home: 'خانه', chats: 'گفتگوها', post: 'ارسال', alerts: 'هشدارها', profile: 'پروفایل', welcomeTitle: 'به Schoolink خوش آمدید', welcomeTagline: 'پلتفرم همه‌کاره شما برای مدارس، کارکنان، والدین و جوامع.', signInEmail: 'ورود با ایمیل', continueGoogle: 'ادامه با Google', continueGuest: 'ادامه به عنوان مهمان', agree: 'با ادامه دادن، شما با موافقت می‌کنید' },
}

const LanguageContext = createContext({ lang: 'en', t: (key) => translations.en[key] || key })

export function LanguageProvider({ children }) {
  const { profile } = useAuth()
  const lang = profile?.language || 'en'

  function t(key) {
    return translations[lang]?.[key] || translations.en[key] || key
  }

  return <LanguageContext.Provider value={{ lang, t }}>{children}</LanguageContext.Provider>
}

export function useTranslation() {
  return useContext(LanguageContext)
       }
